### ISSUE TITLE
CMAKE setup

### ISSUE THREAD

**Issue by CitrusHappy** [xwRongx/cs170-project2#9]

**Comment by Liusdaooo** [comment]
我有一段CMakeTestCXXCompiler.cmake代码 在把YOLOV8部署到Android studio手机上时，报CMake Error at D:/AndroidSDK/cmake/3.10.2.4988404/share/cmake-3.10/Modules/CMakeTestCXXCompiler.cmake:45 (message):
The C++ compiler   怎么解决？
